# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
AWSTemplateFormatVersion: 2010-09-09
Description: "Template for CodeArtifact repositories. Creates Domain if CreateDomainFlag is True"
Parameters:
  DomainName:
    Type: String
    Description: The name of the CodeArtifact Domain
    Default: crypto-tools-internal
  RepositoryName:
    Type: String
    Description: Base Name for the Repositories
    Default: esdk-java
  CreateDomainFlag:
    Type: String
    Description: Attempt to create Domain or not
    Default: False
    AllowedValues:
      - True
      - False

Conditions:
  CreateDomain: !Equals
    - !Ref CreateDomainFlag
    - True

Resources:
  Domain:
    Type: AWS::CodeArtifact::Domain
    Condition: CreateDomain
    Properties:
      DomainName: !Ref DomainName
      Tags:
        - Key: yor_trace
          Value: 1f9f995b-765f-421c-b9e4-9d3af4f84a43
        - Key: manny
          Value: cepeda
        - Key: git_org
          Value: mannycepeda1989
  CIRepo:
    Type: AWS::CodeArtifact::Repository
    Properties:
      DomainName: !Ref DomainName
      RepositoryName: !Sub "${RepositoryName}-ci"
      Tags:
        - Key: git_org
          Value: mannycepeda1989
        - Key: yor_trace
          Value: a6e348f0-89f6-40b7-bddc-08c315f872a7
        - Key: manny
          Value: cepeda
  StagingRepo:
    Type: AWS::CodeArtifact::Repository
    Properties:
      DomainName: !Ref DomainName
      RepositoryName: !Sub "${RepositoryName}-staging"
      Tags:
        - Key: yor_trace
          Value: f9022349-b4f0-4a85-b644-ff59abffdebb
        - Key: manny
          Value: cepeda
        - Key: git_org
          Value: mannycepeda1989
